# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test and Build

on:
  workflow_dispatch:
    inputs:
      description:
        required: false
        default: 'Test and build'
  pull_request:
    branches: [ "master" ]
env:
  PROJECT_DIR: $GITHUB_WORKSPACE

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Test
      run: mvn test

    - name: Build
      run: mvn clean install

    - name: Install dependencies
      run: |
        pip install -r $GITHUB_WORKSPACE/integration/tests/requirements.txt
        sudo chmod a+x $GITHUB_WORKSPACE/integration/scripts/start_db.sh  
        sudo $GITHUB_WORKSPACE/integration/scripts/start_db.sh
        sudo chmod a+x $GITHUB_WORKSPACE/integration/scripts/start_server.sh
        $GITHUB_WORKSPACE/integration/scripts/start_server.sh

    - name: Integration Tests
      run: python3 integration_tests.py
